proxies:
- name: 自动节点-1
  type: http
  server: de6ed842-ti84g0-ti89y3-kcvp.hel1-dc2.ukuaishou.com
  port: 443
  tls: true
  sni: de6ed842-ti84g0-ti89y3-kcvp.hel1-dc2.ukuaishou.com
  skip-cert-verify: false
- name: 自动节点-2
  type: http
  server: 15973ab7-ti84g0-ti89y3-kcvp.nbg1-dc4.ukuaishou.com
  port: 443
  tls: true
  sni: 15973ab7-ti84g0-ti89y3-kcvp.nbg1-dc4.ukuaishou.com
  skip-cert-verify: false
