proxies:
- name: 自动节点-1
  type: http
  server: 1d9baaf4-thx0g0-thx6ob-k9yw.hel1-dc2.ukuaishou.com
  port: 443
  tls: true
  sni: 1d9baaf4-thx0g0-thx6ob-k9yw.hel1-dc2.ukuaishou.com
  skip-cert-verify: false
- name: 自动节点-2
  type: http
  server: bd3e52f7-thx0g0-thx6ob-k9yw.nbg1-dc4.ukuaishou.com
  port: 443
  tls: true
  sni: bd3e52f7-thx0g0-thx6ob-k9yw.nbg1-dc4.ukuaishou.com
  skip-cert-verify: false
